recipe: default.v1
language: en

# '''pipeline:
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: RegexEntityExtractor
# #   - name: LexicalSyntacticFeaturizer
# #   - name: CountVectorsFeaturizer
# #   - name: CountVectorsFeaturizer
# #     analyzer: char_wb
# #     min_ngram: 1
# #     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 300
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   # - name: ResponseSelector
#   #   epochs: 100
#     # constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.05
#     ambiguity_threshold: 0.05
#   - name: "DucklingEntityExtractor"
#     url: "http://localhost:8000"
#     dimensions: ["time", "email"]
#     locale: "en_EN"
#     timezone: "Europe/Rome"
#     timeout : 3
# policies:
#   - name: "MemoizationPolicy"
#     max_history: 5
#   - name: "TEDPolicy"
#     max_history: 5
#     epochs: 100'''
  
# new pipeline
pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SpacyEntityExtractor"
    dimensions: ["PERSON"]
  - name: DIETClassifier
    epochs: 300
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.05
    ambiguity_threshold: 0.05
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: ["time", "email"]
    locale: "en_EN"
    timezone: "Europe/Rome"
    timeout : 3
policies:
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
