recipe: default.v1
language: en
pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SpacyEntityExtractor"
    dimensions: ["PERSON"]
  - name: "RegexFeaturizer"
  - name: "RegexEntityExtractor"
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.05
    ambiguity_threshold: 0.05
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: ["time", "email", "quantity"]
    locale: "en_EN"
    timezone: "Europe/Rome"
    timeout : 3
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat
policies:
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
  - name: "RulePolicy"
